(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
let db={apps:[],stats:{}};
function toast(m,t='success'){window.SpinAppStore?.toast(m,t)}
function val(id){return $(`#${id}`)?.value?.trim()||''}
function set(id,v){const el=$(`#${id}`);if(el)el.value=v??''}
function checked(id){return Boolean($(`#${id}`)?.checked)}
function setChecked(id,v){const el=$(`#${id}`);if(el)el.checked=Boolean(v)}
function parseLines(v){return window.SpinAppStore.parseList(v)}
function logo(app){return window.SpinAppStore.appLogoSrc(app)}
async function boot(){bindAuth();if(window.SpinAuth.isLoggedIn())showDashboard();else showLogin()}
function bindAuth(){const form=$('#loginForm');form?.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button');btn.disabled=true;try{const ok=await window.SpinAuth.verifyPassword($('#adminPassword').value);if(!ok)throw new Error('Mot de passe incorrect.');window.SpinAuth.login();$('#adminPassword').value='';showDashboard();toast('Connexion réussie.','success')}catch(err){toast(err.message,'error')}finally{btn.disabled=false}});$('#logoutBtn')?.addEventListener('click',()=>{window.SpinAuth.logout();showLogin();toast('Session fermée.','success')});$('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();try{await window.SpinAuth.changePassword(val('oldPassword'),val('newPassword'));set('oldPassword','');set('newPassword','');toast('Mot de passe administrateur mis à jour.','success')}catch(err){toast(err.message,'error')}})}
function showLogin(){$('#loginPanel')?.classList.remove('hidden');$('#adminDashboard')?.classList.add('hidden')}
async function showDashboard(){$('#loginPanel')?.classList.add('hidden');$('#adminDashboard')?.classList.remove('hidden');bindDashboard();await load()}
let dashboardBound=false;
function bindDashboard(){if(dashboardBound)return;dashboardBound=true;$('#newAppBtn')?.addEventListener('click',()=>resetForm(true));$('#exportBtn')?.addEventListener('click',exportJson);$('#importFile')?.addEventListener('change',importJson);$('#resetLocalBtn')?.addEventListener('click',async()=>{if(confirm('Supprimer les données locales et revenir à data/apps.json ?')){window.SpinAppStore.clearLocalDatabase();await load();toast('Données locales réinitialisées.','success')}});$('#appForm')?.addEventListener('submit',saveApp);$('#cancelEditBtn')?.addEventListener('click',()=>resetForm());$('#appsList')?.addEventListener('click',listAction)}
async function load(){db=await window.SpinAppStore.loadDatabase();renderStats();renderList();renderJsonPreview();resetForm()}
function renderStats(){const cats=window.SpinAppStore.categories(db.apps).length;$('#adminStats').innerHTML=[['Applications',db.stats.totalApps],['Téléchargements',db.stats.totalDownloads],['Catégories',cats],['Mise à jour',db.stats.lastUpdate||'—']].map(x=>`<article class="admin-stat"><strong>${x[1]}</strong><span>${x[0]}</span></article>`).join('')}
function renderList(){const wrap=$('#appsList');if(!db.apps.length){wrap.innerHTML='<div class="empty-admin">Aucune application pour l’instant. Cliquez sur “Ajouter une application” et construisez votre catalogue premium.</div>';return}wrap.innerHTML=`<div class="apps-table-wrap"><table class="apps-table"><thead><tr><th>Application</th><th>Catégorie</th><th>Version</th><th>APK</th><th>Téléch.</th><th>Actions</th></tr></thead><tbody>${db.apps.map(app=>`<tr><td><div class="table-app"><img src="${window.SpinAppStore.escapeAttr(logo(app))}" alt="" data-fallback-logo data-app-name="${window.SpinAppStore.escapeAttr(app.name)}"><span>${window.SpinAppStore.escapeHTML(app.name)}</span></div></td><td>${window.SpinAppStore.escapeHTML(app.category)}</td><td>v${window.SpinAppStore.escapeHTML(app.version)}</td><td>${app.apkUrl?'<span class="status-badge">Lien prêt</span>':'<span class="status-badge">À ajouter</span>'}</td><td>${app.downloads}</td><td><div class="row-actions"><button class="btn btn-secondary btn-small" data-action="edit" data-id="${app.id}">Modifier</button><a class="btn btn-ghost btn-small" href="app-detail.html?id=${encodeURIComponent(app.id)}" target="_blank">Voir</a><button class="btn btn-danger btn-small" data-action="delete" data-id="${app.id}">Supprimer</button></div></td></tr>`).join('')}</tbody></table></div>`}
function renderJsonPreview(){$('#jsonPreview').textContent=JSON.stringify(db,null,2)}
function resetForm(scroll=false){$('#formTitle').textContent='Ajouter une application';$('#appForm').reset();set('appId','');set('updatedAt',new Date().toISOString().slice(0,10));set('android','Android 8.0+');set('version','1.0.0');set('trialDays','7');set('downloads','0');set('rating','0');setChecked('featured',false);if(scroll)$('#appForm').scrollIntoView({behavior:'smooth',block:'start'})}
function fillForm(app){$('#formTitle').textContent='Modifier une application';set('appId',app.id);set('name',app.name);set('version',app.version);set('category',app.category);set('shortDescription',app.shortDescription);set('description',app.description);set('apkUrl',app.apkUrl);set('sizeMb',app.sizeMb);set('logoUrl',app.logo);set('screenshots',app.screenshots.join('\n'));set('monthlyPrice',app.pricing.monthly);set('annualPrice',app.pricing.annual);set('trialDays',app.pricing.trialDays);set('features',app.features.join('\n'));set('android',app.tech.android);set('updatedAt',app.tech.updatedAt);set('downloads',app.downloads);set('rating',app.rating);setChecked('featured',app.featured);$('#appForm').scrollIntoView({behavior:'smooth',block:'start'})}
function appFromForm(){const name=val('name');if(!name)throw new Error('Le nom de l’application est obligatoire.');const id=val('appId')||`${window.SpinAppStore.slugify(name)}-${Date.now().toString(36).slice(-5)}`;return{id,name,version:val('version')||'1.0.0',category:val('category')||'Général',shortDescription:val('shortDescription'),description:val('description'),apkUrl:val('apkUrl'),sizeMb:val('sizeMb'),logo:val('logoUrl'),screenshots:parseLines(val('screenshots')),pricing:{monthly:val('monthlyPrice'),annual:val('annualPrice'),trialDays:val('trialDays')},features:parseLines(val('features')),tech:{android:val('android')||'Android 8.0+',updatedAt:val('updatedAt')||new Date().toISOString().slice(0,10)},downloads:Number(val('downloads')||0),rating:Number(val('rating')||0),featured:checked('featured')}}
function saveApp(e){e.preventDefault();try{const app=window.SpinAppStore.normalizeApp(appFromForm());const i=db.apps.findIndex(a=>a.id===app.id);if(i>=0)db.apps[i]=app;else db.apps.push(app);db=window.SpinAppStore.saveDatabase(db);renderStats();renderList();renderJsonPreview();resetForm();toast('Application enregistrée localement. Exportez apps.json pour publier sur GitHub.','success')}catch(err){toast(err.message,'error')}}
function listAction(e){const btn=e.target.closest('[data-action]');if(!btn)return;const id=btn.dataset.id;const app=db.apps.find(a=>a.id===id);if(!app)return;if(btn.dataset.action==='edit')fillForm(app);if(btn.dataset.action==='delete'&&confirm(`Supprimer ${app.name} ?`)){db.apps=db.apps.filter(a=>a.id!==id);db=window.SpinAppStore.saveDatabase(db);renderStats();renderList();renderJsonPreview();toast('Application supprimée.','success')}}
function exportJson(){const data=JSON.stringify(window.SpinAppStore.normalizeDatabase(db),null,2);const blob=new Blob([data],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='apps.json';document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove();toast('Fichier apps.json exporté. Remplacez data/apps.json dans GitHub.','success')}
function importJson(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);db=window.SpinAppStore.saveDatabase(parsed);renderStats();renderList();renderJsonPreview();toast('Catalogue importé avec succès.','success')}catch(err){toast('JSON invalide : '+err.message,'error')}finally{e.target.value=''}};reader.readAsText(file)}
document.addEventListener('DOMContentLoaded',boot);
})();
