(function(){
'use strict';
const CONFIG={dbUrl:'data/apps.json',storageKey:'spinapp-apps-db',downloadEventsKey:'spinapp-download-events',today:'2026-07-06'};
const DEFAULT_DB={apps:[],stats:{totalApps:0,totalDownloads:0,lastUpdate:CONFIG.today}};
const PLACEHOLDER='assets/stickers/screenshot-placeholder.svg';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function clone(v){return JSON.parse(JSON.stringify(v))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function attr(v){return esc(v).replace(/`/g,'&#96;')}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function today(){try{return new Date().toISOString().slice(0,10)}catch(e){return CONFIG.today}}
function slug(v){return String(v||'application').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'application'}
function safeUrl(u){const v=String(u||'').trim();return (!v||/^javascript:/i.test(v)||/^data:text\/html/i.test(v))?'':v}
function parseList(v){if(!v)return[];if(Array.isArray(v))return v.map(x=>String(x).trim()).filter(Boolean);return String(v).split(/[\n,]+/).map(x=>x.trim()).filter(Boolean)}
function truncate(v,l=138){const t=String(v||'').trim();return t.length<=l?t:t.slice(0,l-1).trim()+'…'}
function initials(n){const p=String(n||'SpinApp').trim().split(/\s+/).filter(Boolean);return (p.length>1?(p[0][0]+p[1][0]):(p[0]||'SA').slice(0,2)).toUpperCase()}
function hsl(n,o=0){let h=0;String(n||'SpinApp').split('').forEach(ch=>h=ch.charCodeAt(0)+((h<<5)-h));return `hsl(${Math.abs(h+o)%360},78%,46%)`}
function generatedLogo(name){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 180 180"><defs><linearGradient id="g" x1="0" x2="180" y1="0" y2="180"><stop stop-color="${hsl(name,20)}"/><stop offset="1" stop-color="${hsl(name,110)}"/></linearGradient></defs><rect width="180" height="180" rx="46" fill="url(#g)"/><path d="M42 112c20 25 73 25 96 0" fill="none" stroke="#fff" stroke-width="10" stroke-linecap="round" opacity=".62"/><path d="M90 42c44 4 64 50 36 78-23 23-69 11-70-22-1-25 31-38 48-20 13 14 3 37-18 35" fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round" opacity=".82"/><text x="50%" y="61%" text-anchor="middle" font-family="Arial,sans-serif" font-size="52" font-weight="900" fill="#fff">${esc(initials(name))}</text></svg>`;return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function normalizeApp(a={}){const name=String(a.name||a.nom||'Application sans nom').trim();const pricing=a.pricing||{},tech=a.tech||{};return{id:String(a.id||slug(name)).trim(),name,version:String(a.version||'1.0.0').trim(),category:String(a.category||'Général').trim(),shortDescription:String(a.shortDescription||a.descriptionShort||a.short||'').trim(),description:String(a.description||a.longDescription||a.descriptionComplete||'').trim(),apkUrl:safeUrl(a.apkUrl||a.apk||a.downloadUrl||''),sizeMb:String(a.sizeMb||a.size||'').trim(),logo:safeUrl(a.logo||a.logoUrl||''),screenshots:parseList(a.screenshots).map(safeUrl).filter(Boolean),pricing:{monthly:pricing.monthly??a.monthlyPrice??'',annual:pricing.annual??a.annualPrice??'',trialDays:pricing.trialDays??a.trialDays??''},features:parseList(a.features),tech:{android:String(tech.android||a.android||'Android 8.0+').trim(),updatedAt:String(tech.updatedAt||a.updatedAt||a.lastUpdate||CONFIG.today).trim()},downloads:num(a.downloads,0),rating:num(a.rating,0),featured:Boolean(a.featured)}}
function normalizeDatabase(raw){const s=raw&&typeof raw==='object'?raw:clone(DEFAULT_DB);const apps=Array.isArray(s.apps)?s.apps.map(normalizeApp):[];return{apps,stats:{totalApps:apps.length,totalDownloads:apps.reduce((m,a)=>m+num(a.downloads),0),lastUpdate:String(s.stats?.lastUpdate||s.lastUpdate||CONFIG.today)}}}
async function loadDatabase(opt={}){let db=clone(DEFAULT_DB);if(!opt.localOnly){try{const r=await fetch(`${CONFIG.dbUrl}?v=${Date.now()}`,{cache:'no-store'});if(r.ok)db=await r.json()}catch(e){}}try{const local=localStorage.getItem(CONFIG.storageKey);if(local&&!opt.ignoreLocal)db=JSON.parse(local)}catch(e){console.warn('SpinApp local data error',e)}return normalizeDatabase(db)}
function saveDatabase(db){const n=normalizeDatabase({...db,stats:{...(db.stats||{}),lastUpdate:today()}});localStorage.setItem(CONFIG.storageKey,JSON.stringify(n,null,2));window.dispatchEvent(new CustomEvent('spinapp:database-updated',{detail:n}));return n}
function clearLocalDatabase(){localStorage.removeItem(CONFIG.storageKey);window.dispatchEvent(new CustomEvent('spinapp:database-updated'))}
function categories(apps){return [...new Set((apps||[]).map(a=>a.category||'Général'))].sort((a,b)=>a.localeCompare(b,'fr'))}
function sortLatest(apps){return [...apps].sort((a,b)=>{if(Boolean(a.featured)!==Boolean(b.featured))return b.featured-a.featured;return String(b.tech.updatedAt||'').localeCompare(String(a.tech.updatedAt||''))})}
function price(v){if(v===''||v==null)return 'À définir';const n=Number(v);if(!Number.isFinite(n)||n<=0)return 'Gratuit / à confirmer';return `${n.toFixed(n%1?2:0)} $`}
function dateFmt(v){if(!v)return 'À définir';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'long',year:'numeric'}).format(d)}
function summary(a){return a.shortDescription||truncate(a.description)||'Une solution Spirale Agence prête à rejoindre votre quotidien digital.'}
function logo(a){return safeUrl(a.logo)||generatedLogo(a.name)}
function icon(n){const i={apps:'<svg class="icon" viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="6" height="6" rx="2" stroke="currentColor" stroke-width="2"/><rect x="14" y="4" width="6" height="6" rx="2" stroke="currentColor" stroke-width="2"/><rect x="4" y="14" width="6" height="6" rx="2" stroke="currentColor" stroke-width="2"/><rect x="14" y="14" width="6" height="6" rx="2" stroke="currentColor" stroke-width="2"/></svg>',download:'<svg class="icon" viewBox="0 0 24 24" fill="none"><path d="M12 3v11m0 0 4-4m-4 4-4-4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 17v2a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',shield:'<svg class="icon" viewBox="0 0 24 24" fill="none"><path d="M12 3 5 6v5c0 4.4 2.8 7.9 7 10 4.2-2.1 7-5.6 7-10V6l-7-3Z" stroke="currentColor" stroke-width="2"/><path d="m9 12 2 2 4-5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',arrow:'<svg class="icon" viewBox="0 0 24 24" fill="none"><path d="M5 12h14m0 0-5-5m5 5-5 5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',search:'<svg class="icon" viewBox="0 0 24 24" fill="none"><path d="m21 21-4.3-4.3M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4Z" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',star:'<svg class="icon" viewBox="0 0 24 24" fill="currentColor"><path d="m12 2.8 2.8 5.7 6.3.9-4.55 4.45 1.08 6.28L12 17.17l-5.63 2.96 1.08-6.28L2.9 9.4l6.3-.9L12 2.8Z"/></svg>'};return i[n]||''}
function appCard(a){const dh=safeUrl(a.apkUrl);const dl=dh?`<a class="btn btn-primary btn-small" href="${attr(dh)}" data-download-id="${attr(a.id)}" target="_blank" rel="noopener">${icon('download')} APK</a>`:`<button class="btn btn-small btn-disabled" type="button" data-no-apk aria-disabled="true">APK bientôt</button>`;return `<article class="app-card" data-app-card data-category="${attr(a.category)}"><div class="app-card-visual"><span class="category-badge">${esc(a.category)}</span><img class="app-logo" src="${attr(logo(a))}" alt="Logo ${attr(a.name)}" data-fallback-logo data-app-name="${attr(a.name)}"></div><h3>${esc(a.name)}</h3><p>${esc(summary(a))}</p><div class="card-meta"><span class="meta-chip">v${esc(a.version)}</span><span class="meta-chip">${esc(a.sizeMb||'Taille à définir')}${a.sizeMb&&!String(a.sizeMb).toLowerCase().includes('mb')?' MB':''}</span><span class="meta-chip">${esc(a.tech.android||'Android')}</span></div><div class="card-actions"><a class="btn btn-secondary btn-small" href="app-detail.html?id=${encodeURIComponent(a.id)}">Détails ${icon('arrow')}</a>${dl}</div></article>`}
function emptyState(title='Catalogue bientôt disponible',msg='Les applications Spirale Agence seront présentées ici avec clarté, précision et téléchargement direct dès leur publication.',action=false){return `<div class="empty-state"><img src="assets/stickers/empty-catalog.svg" alt="Catalogue vide"><h3>${esc(title)}</h3><p>${esc(msg)}</p>${action?'<a class="btn btn-primary" href="admin.html">Ouvrir le portail administrateur</a>':''}</div>`}
function toast(m,type='success'){let r=$('.toast-root');if(!r){r=document.createElement('div');r.className='toast-root';document.body.appendChild(r)}const it=document.createElement('div');it.className=`toast ${type}`;it.textContent=m;r.appendChild(it);setTimeout(()=>it.remove(),4200)}
async function incrementDownload(id){if(!id)return;const db=await loadDatabase();const i=db.apps.findIndex(a=>a.id===id);if(i>=0){db.apps[i].downloads=num(db.apps[i].downloads)+1;saveDatabase(db)}try{const ev=JSON.parse(localStorage.getItem(CONFIG.downloadEventsKey)||'[]');ev.push({appId:id,at:new Date().toISOString()});localStorage.setItem(CONFIG.downloadEventsKey,JSON.stringify(ev.slice(-500)))}catch(e){}}
function registerDownloadHandlers(){if(window.__spinDownloadHandlersRegistered)return;window.__spinDownloadHandlersRegistered=true;document.addEventListener('click',e=>{const no=e.target.closest('[data-no-apk]');if(no){e.preventDefault();toast('Cette application attend encore son lien APK. Elle sera disponible dès la publication officielle.','warning');return}const l=e.target.closest('[data-download-id]');if(l){incrementDownload(l.getAttribute('data-download-id'));toast('Téléchargement lancé. Merci de faire confiance à Spirale Agence.','success')}});document.addEventListener('error',e=>{const im=e.target;if(!(im instanceof HTMLImageElement))return;if(im.matches('[data-fallback-logo]'))im.src=generatedLogo(im.getAttribute('data-app-name')||'SpinApp');if(im.matches('[data-screenshot]'))im.src=PLACEHOLDER},true)}
async function renderHome(){const db=await loadDatabase();const latest=$('[data-latest-apps]');if(latest){const apps=sortLatest(db.apps).slice(0,4);latest.innerHTML=apps.length?apps.map(appCard).join(''):emptyState('La vitrine est installée','Le catalogue est vide pour le moment. Ajoutez vos applications Spirale et transformez ce bloc en rayon de téléchargement premium.')}const st=$('[data-home-stats]');if(st){const cats=categories(db.apps).length;const rating=db.apps.length?(db.apps.reduce((s,a)=>s+num(a.rating),0)/db.apps.length).toFixed(1):'0.0';st.innerHTML=[{label:'Applications publiées',value:db.stats.totalApps,icon:'apps'},{label:'Téléchargements suivis',value:db.stats.totalDownloads,icon:'download'},{label:'Catégories prêtes',value:cats,icon:'shield'},{label:'Note moyenne',value:rating,icon:'star'}].map(x=>`<article class="stat-card"><span class="stat-icon">${icon(x.icon)}</span><div><strong>${esc(x.value)}</strong><span>${esc(x.label)}</span></div></article>`).join('')}}
async function renderCatalog(){const grid=$('[data-apps-catalog]');if(!grid)return;const search=$('[data-app-search]'),select=$('[data-app-category]'),pills=$('[data-category-pills]'),count=$('[data-catalog-count]'),pagination=$('[data-pagination]');const db=await loadDatabase();let cat='Tous',page=1;const per=8;function buildFilters(){const cats=categories(db.apps);if(select)select.innerHTML=['Tous',...cats].map(c=>`<option value="${attr(c)}">${esc(c)}</option>`).join('');if(pills)pills.innerHTML=['Tous',...cats].map((c,i)=>`<button class="filter-pill ${i?'':'active'}" type="button" data-filter-category="${attr(c)}">${esc(c)}</button>`).join('')}function filtered(){const q=String(search?.value||'').trim().toLowerCase();return sortLatest(db.apps).filter(a=>{const hay=[a.name,a.category,a.shortDescription,a.description,a.features.join(' ')].join(' ').toLowerCase();return (cat==='Tous'||a.category===cat)&&(!q||hay.includes(q))})}function setCat(c){cat=c||'Tous';page=1;if(select)select.value=cat;$$('.filter-pill',pills||document).forEach(b=>b.classList.toggle('active',b.dataset.filterCategory===cat));render()}function render(){const apps=filtered();const pages=Math.max(1,Math.ceil(apps.length/per));page=Math.min(page,pages);const slice=apps.slice((page-1)*per,(page-1)*per+per);grid.innerHTML=slice.length?slice.map(appCard).join(''):emptyState('Aucune application trouvée','Ajustez la recherche ou la catégorie. Le catalogue Spirale reste prêt à recevoir de nouvelles solutions.',false);if(count)count.textContent=`${apps.length} application${apps.length>1?'s':''} affichée${apps.length>1?'s':''}`;if(pagination)pagination.innerHTML=pages>1?Array.from({length:pages},(_,i)=>i+1).map(p=>`<button class="page-btn ${p===page?'active':''}" type="button" data-page-number="${p}">${p}</button>`).join(''):''}buildFilters();render();search?.addEventListener('input',()=>{page=1;render()});select?.addEventListener('change',()=>setCat(select.value));pills?.addEventListener('click',e=>{const b=e.target.closest('[data-filter-category]');if(b)setCat(b.dataset.filterCategory)});pagination?.addEventListener('click',e=>{const b=e.target.closest('[data-page-number]');if(b){page=Number(b.dataset.pageNumber)||1;render();grid.scrollIntoView({behavior:'smooth',block:'start'})}})}
function screenshots(a){
  const list=a.screenshots.length?a.screenshots:[PLACEHOLDER,PLACEHOLDER,PLACEHOLDER,PLACEHOLDER];
  return `<div class="screenshot-carousel" aria-label="Captures d’écran défilantes de ${attr(a.name)}">${list.slice(0,8).map((src,i)=>`<figure class="screenshot-frame"><img src="${attr(src)}" alt="Capture ${i+1} de ${attr(a.name)}" data-screenshot><figcaption>Capture ${i+1}</figcaption></figure>`).join('')}</div>`
}
function accordion(title,content,open=false){return `<details class="accordion-card" ${open?'open':''}><summary>${esc(title)}</summary>${content}</details>`}
async function renderDetail(){
  const root=$('[data-app-detail]');if(!root)return;
  const id=new URLSearchParams(location.search).get('id');
  const db=await loadDatabase();
  const a=db.apps.find(x=>x.id===id)||null;
  if(!a){root.innerHTML=emptyState('Application introuvable','Revenez au catalogue pour choisir une solution Spirale disponible.',false);return}
  const features=a.features.length?a.features:['Téléchargement direct en APK','Présentation professionnelle','Support Spirale Agence via WhatsApp'];
  const related=sortLatest(db.apps).filter(x=>x.id!==a.id&&x.category===a.category).slice(0,2);
  const dh=safeUrl(a.apkUrl);
  const download=dh?`<a class="btn btn-primary" href="${attr(dh)}" data-download-id="${attr(a.id)}" target="_blank" rel="noopener">${icon('download')} Télécharger APK</a>`:`<button class="btn btn-disabled" data-no-apk aria-disabled="true">APK bientôt disponible</button>`;
  const description=accordion('Description complète',`<p>${esc(a.description||summary(a))}</p>`,true);
  const featurePanel=accordion('Fonctionnalités clés',`<ul class="feature-list">${features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>`);
  const pricingPanel=accordion('Tarifs',`<div class="price-row"><span>Mensuel</span><strong>${price(a.pricing.monthly)}</strong></div><div class="price-row"><span>Annuel</span><strong>${price(a.pricing.annual)}</strong></div><div class="price-row"><span>Essai</span><strong>${a.pricing.trialDays?esc(a.pricing.trialDays)+' jours':'À définir'}</strong></div>`);
  const techPanel=accordion('Informations techniques',`<div class="tech-row"><span>Taille</span><strong>${esc(a.sizeMb||'À définir')}${a.sizeMb&&!String(a.sizeMb).toLowerCase().includes('mb')?' MB':''}</strong></div><div class="tech-row"><span>Compatibilité</span><strong>${esc(a.tech.android)}</strong></div><div class="tech-row"><span>Mise à jour</span><strong>${dateFmt(a.tech.updatedAt)}</strong></div><div class="tech-row"><span>Téléchargements</span><strong>${esc(a.downloads)}</strong></div>`);
  const reviewPanel=accordion('Avis utilisateurs',`<div class="review-card"><strong class="rating-stars">${'★'.repeat(Math.round(num(a.rating))||0)}${'☆'.repeat(5-(Math.round(num(a.rating))||0))}</strong><p>${num(a.rating)>0?'Une note utile pour mesurer la confiance autour de cette application.':'Les avis apparaîtront ici dès les premiers retours utilisateurs.'}</p></div>`);
  root.innerHTML=`<section class="detail-hero"><div class="detail-main"><img class="detail-logo" src="${attr(logo(a))}" alt="Logo ${attr(a.name)}" data-fallback-logo data-app-name="${attr(a.name)}"><div><span class="category-badge">${esc(a.category)}</span><h1 class="detail-title">${esc(a.name)}</h1><p>${esc(summary(a))}</p></div></div><div class="detail-actions"><span class="meta-chip">Version ${esc(a.version)}</span>${download}</div></section><section class="detail-section screenshot-section"><div class="section-head compact-head"><div><p class="eyebrow">Captures d’écran</p><h2>Glissez de gauche à droite.</h2></div><p>Un aperçu visuel fluide, pensé pour présenter l’application sans alourdir la page.</p></div>${screenshots(a)}</section><section class="detail-section"><div class="accordion-stack detail-accordions">${description}${featurePanel}${pricingPanel}${techPanel}${reviewPanel}</div></section>${related.length?`<section class="detail-section"><div class="section-head compact-head"><div><p class="eyebrow">Même univers</p><h2>À découvrir aussi.</h2></div></div><div class="related-grid">${related.map(appCard).join('')}</div></section>`:''}`;
  document.title=`${a.name} - SpinApp Distribution`;
}
window.SpinAppStore={CONFIG,loadDatabase,saveDatabase,clearLocalDatabase,normalizeDatabase,normalizeApp,parseList,slugify:slug,generatedLogo,appLogoSrc:logo,appCard,emptyState,toast,renderHome,renderCatalog,renderDetail,registerDownloadHandlers,categories,formatPrice:price,formatDate:dateFmt,escapeHTML:esc,escapeAttr:attr,icons:icon};
document.addEventListener('DOMContentLoaded',registerDownloadHandlers);
})();
