(function(){
'use strict';
function qs(s,r=document){return r.querySelector(s)}
function qsa(s,r=document){return Array.from(r.querySelectorAll(s))}
function setActiveNav(){const page=document.body.dataset.page||'home';qsa('[data-nav]').forEach(a=>a.setAttribute('aria-current',a.dataset.nav===page?'page':'false'))}
function initNav(){const bar=qs('[data-navbar]'),btn=qs('[data-nav-toggle]');if(!bar||!btn)return;btn.addEventListener('click',()=>{const open=bar.classList.toggle('nav-open');btn.setAttribute('aria-expanded',String(open))});qsa('.nav-link',bar).forEach(a=>a.addEventListener('click',()=>{bar.classList.remove('nav-open');btn.setAttribute('aria-expanded','false')}))}
function initCopyLinks(){qsa('[data-copy]').forEach(el=>el.addEventListener('click',async e=>{e.preventDefault();const value=el.getAttribute('data-copy')||el.textContent.trim();try{await navigator.clipboard.writeText(value);window.SpinAppStore?.toast('Contact copié avec succès.','success')}catch(_){window.SpinAppStore?.toast(value,'success')}}))}
function initContactForm(){const form=qs('[data-contact-form]');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const name=String(data.get('name')||'').trim();const contact=String(data.get('contact')||'').trim();const wish=String(data.get('wish')||'').trim();const message=String(data.get('message')||'').trim();if(!name||!contact||!wish){window.SpinAppStore?.toast('Ajoutez votre nom, votre contact et votre envie pour continuer.','warning');return}const recipient=['erikaekepler','gmail.com'].join('@');const subject=`SpinApp - Nouvelle envie application de ${name}`;const body=[`Nom : ${name}`,`Contact : ${contact}`,`Envie application : ${wish}`,message?`Message : ${message}`:'','—','Envoyé depuis SpinApp Distribution'].filter(Boolean).join('\n');window.location.href=`mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.SpinAppStore?.toast('Votre application email va s’ouvrir pour envoyer la demande.','success');form.reset()})}
function initYear(){qsa('[data-year]').forEach(el=>el.textContent='2026')}
function initRoute(){const page=document.body.dataset.page;if(page==='home')window.SpinAppStore?.renderHome();if(page==='catalog')window.SpinAppStore?.renderCatalog();if(page==='detail')window.SpinAppStore?.renderDetail()}
function refreshOnLocalUpdate(){window.addEventListener('spinapp:database-updated',()=>{const page=document.body.dataset.page;if(page==='home')window.SpinAppStore?.renderHome();if(page==='catalog')window.SpinAppStore?.renderCatalog();if(page==='detail')window.SpinAppStore?.renderDetail()})}
document.addEventListener('DOMContentLoaded',()=>{setActiveNav();initNav();initCopyLinks();initContactForm();initYear();initRoute();refreshOnLocalUpdate()});
})();
